// backend/config/rbac.js
const ROLES = {
    ADMIN: 'ADMIN',
    STUDENT: 'STUDENT',
    TEACHER: 'TEACHER'
};

const PERMISSIONS = {
    CREATE_USER: 'CREATE_USER',
    READ_USER: 'READ_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    MANAGE_COURSES: 'MANAGE_COURSES'
};

const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: [
        PERMISSIONS.CREATE_USER,
        PERMISSIONS.READ_USER,
        PERMISSIONS.UPDATE_USER,
        PERMISSIONS.DELETE_USER,
        PERMISSIONS.MANAGE_COURSES
    ],
    [ROLES.TEACHER]: [
        PERMISSIONS.READ_USER,
        PERMISSIONS.MANAGE_COURSES
    ],
    [ROLES.STUDENT]: [
        PERMISSIONS.READ_USER
    ]
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
